### PR TITLE
Copyright and branding revamp

### PR DESCRIPTION
**Pull request by rsdy**

### CODE REVIEW

**Review by rhdxmr — COMMENTED** [review]
This project is re-licensed from `GPLv3` to `Apache v2`.
I think it is permitted because you are a copyright holder and nobody has contributed their code to this project under GPLv3

**Review by rhdxmr — APPROVED** [review]
I didn't read very long lines that never wrap and that with changed sha256 digest.
Those lines are really hard to read so I could not find any flaws by naked eyes.
I just assume that everything is OK.

I read some changed footers that specify `ingrand`, `RedBPF`, `CC-BY-4.0` and `TLF`. These are Looks Good to me. But is it planned to rename `ingraind` soon? So the documents will be changed again with new name?

**Review by rhdxmr — CHANGES_REQUESTED** [review]
Umm.. I just forked the repo and tested in localhost but the site seems corrupted

**Comment by rhdxmr** [comment]
image

**Comment by rhdxmr** [comment]
But it works OK with `master` branch in my localhost. So some modification from this PR incurs this error.

**Comment by rhdxmr** [comment]
With `master` branch in my localhost, site works correctly

image

**Comment by rsdy** [comment]
@rhdxmr That's correct, I failed to upload the CSS. Works on my box now.

image

**Review by rhdxmr — APPROVED** [review]
LGTM :+1:

**Pull request merged**
